{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{def $idstart="ContentObjectAttribute_"
     $idend=concat("_",$attribute.id)
     $event=$attribute.content
     $locale = fetch('content', 'locale')
     $english_weekday_name_list = array( 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday' )
     }
{*$attribute.content|attribute(show)*}
{ezscript_require( array('ezjsc::jquery', 'bcalendar.js') )}
{ezcss_require( array( 'blendcalendar.css' ) )}
<script type="text/javascript">
<!--
var blendCalendarWeekString = "{'week(s)'|i18n('blendcalendar')}";
var blendCalendarMonthString = "{'month(s)'|i18n('blendcalendar')}";
var blendCalendarYearString = "{'year(s)'|i18n('blendcalendar')}";
//-->
</script>

    <div class="block bc-event-block">
        <div class="block bc-element-occurs">
            <label class="inline" for="{$idstart}recurtype{$idend}">{'Occurs:'|i18n('blendcalendar')}</label>
            <select class="bc-recurtype" name="{$idstart}recurtype{$idend}" id="{$idstart}recurtype{$idend}">
                <option value="ONCE" {if $event.recurrence_type|eq(1)}selected="selected" {/if}>{'Once'|i18n('blendcalendar')}</option>
                <option value="WEEK" {if $event.recurrence_type|eq(2)}selected="selected" {/if}>{'Every Week'|i18n('blendcalendar')}</option>
                <option value="MONTH" {if or($event.recurrence_type|eq(4),$event.recurrence_type|eq(8))}selected="selected" {/if}>{'Every Month'|i18n('blendcalendar')}</option>
                <option value="YEAR" {if or($event.recurrence_type|eq(16),$event.recurrence_type|eq(32))}selected="selected" {/if}>{'Every Year'|i18n('blendcalendar')}</option>
            </select>
        </div>
        <div class="bc-recurs">
            <div class="block bc-block-single bc-recurblock" {if $event.recurrence_type|ne(1)}style="display:none" {/if}>
                <label class="inline" for="{$idstart}singledate{$idend}">{'on'|i18n('blendcalendar')}</label>
                <input type="text"  name="{$idstart}singledate{$idend}" id="{$idstart}singledate{$idend}" class="bc-date"
                       value="{if $event.recurrence_type|eq(1)}{$event.singledate}{else}{$event.range_start|l10n('shortdate')}{/if}"
                        />
            </div>
            <div class="block bc-block-weekly bc-recurblock" {if $event.recurrence_type|ne(2)}style="display:none" {/if}>
                {'on'|i18n('blendcalendar')}
            {foreach $locale.weekday_short_name_list as $index => $weekday_short_name}
                <input type="checkbox" name="{$idstart}weekdays{$idend}[]"
                       id="{$idstart}weekdays{$idend}_{$index}" value="{$index}" {if $event[$english_weekday_name_list[$index]]}checked="checked"{/if} />
                <label class="inline" for="{$idstart}weekdays{$idend}_{$index}">{$weekday_short_name|wash}</label>
            {/foreach}
            </div>
            <div class="block bc-block-monthly bc-recurblock" {if and($event.recurrence_type|ne(4),$event.recurrence_type|ne(8))}style="display:none"{/if} >
                <div class="block">
                    <input type="radio" name="{$idstart}monthrecurtype{$idend}" id="{$idstart}monthrecurtype{$idend}_static" {if $event.recurrence_type|eq(4)}checked="checked"{/if} value="MONTHSTATIC" />
                    <label class="inline" for="{$idstart}monthrecurtype{$idend}_static">{'on the'|i18n('blendcalendar')}</label>
                    <select name="{$idstart}monthstaticrecurdate{$idend}">
                        {for 1 to 31 as $day}
                            <option value="{$day}" {if $event.day|eq($day)}selected="selected"{/if} >{$day}</option>
                        {/for}
                    </select>
                </div>
                <div class="block">
                    <input type="radio" name="{$idstart}monthrecurtype{$idend}" id="{$idstart}monthrecurtype{$idend}_relative" {if $event.recurrence_type|eq(8)}checked="checked"{/if}  value="MONTHRELATIVE" />
                    <label class="inline" for="{$idstart}monthrelativeweek{$idend}">{'on the'|i18n('blendcalendar')}</label>
                    <select name="{$idstart}monthrelativeweek{$idend}" id="{$idstart}monthrelativeweek{$idend}">
                        <option {if $event.week|eq(1)}selected="selected" {/if} value="1" >{'First'|i18n('blendcalendar')}</option>
                        <option {if $event.week|eq(2)}selected="selected" {/if} value="2" >{'Second'|i18n('blendcalendar')}</option>
                        <option {if $event.week|eq(3)}selected="selected" {/if} value="3" >{'Third'|i18n('blendcalendar')}</option>
                        <option {if $event.week|eq(4)}selected="selected" {/if} value="4" >{'Fourth'|i18n('blendcalendar')}</option>
                        <!--<option {if $event.week|eq(-1)}selected="selected" {/if} value="-1" >Last</option>-->
                    </select>
                    <select name="{$idstart}monthrelativeday{$idend}" id="{$idstart}monthrelativeday{$idend}">
                        {foreach $locale.weekday_name_list as $index => $weekday_name}
                            <option value="{$index}" {if $event[$english_weekday_name_list[$index]]}selected="selected" {/if}>{$weekday_name|wash}</option>
                        {/foreach}
                    </select> {'of the month'|i18n('blendcalendar')}
                </div>
            </div>
            <div class="block bc-block-yearly bc-recurblock" {if and($event.recurrence_type|ne(16),$event.recurrence_type|ne(32))}style="display:none"{/if} >
                <div class="block">
                    <input type="radio" name="{$idstart}yearrecurtype{$idend}" id="{$idstart}yearrecurtype{$idend}_static" {if $event.recurrence_type|eq(16)}checked="checked"{/if} value="YEARSTATIC" />
                    <label class="inline" for="{$idstart}yearrecurtype{$idend}_static">{'on'|i18n('blendcalendar')}</label>
                    <select name="{$idstart}yearstaticrecurmonth{$idend}">
                        {for 1 to 12 as $month}
                            {def $dt=makedate($month, 1,2001)}
                            <option {if $event.month|eq($month)}selected="selected" {/if}value="{$month}">{$dt|datetime('custom', '%F')}</option>
                            {undef $dt}
                        {/for}
                    </select>
                    <select name="{$idstart}yearstaticrecurdate{$idend}">
                        {for 1 to 31 as $day}
                            <option {if $event.day|eq($day)}selected="selected" {/if}value="{$day}">{$day}</option>
                        {/for}
                    </select>
                </div>
                <div class="block">
                    <input type="radio" name="{$idstart}yearrecurtype{$idend}" id="{$idstart}yearrecurtype{$idend}_relative" {if $event.recurrence_type|eq(32)}checked="checked"{/if} value="YEARRELATIVE" />
                    <label class="inline" for="{$idstart}yearrelativeweek{$idend}">{'on the'|i18n('blendcalendar')}</label>
                    <select name="{$idstart}yearrelativeweek{$idend}" id="{$idstart}yearrelativeweek{$idend}">
                        <option {if $event.week|eq(1)}selected="selected" {/if} value="1" >{'First'|i18n('blendcalendar')}</option>
                        <option {if $event.week|eq(2)}selected="selected" {/if} value="2" >{'Second'|i18n('blendcalendar')}</option>
                        <option {if $event.week|eq(3)}selected="selected" {/if} value="3" >{'Third'|i18n('blendcalendar')}</option>
                        <option {if $event.week|eq(4)}selected="selected" {/if} value="4" >{'Fourth'|i18n('blendcalendar')}</option>
                        <!--<option {if $event.week|eq(-1)}selected="selected" {/if} value="-1" >Last</option>-->
                    </select>
                    <select name="{$idstart}yearrelativeday{$idend}" id="{$idstart}yearrelativeday{$idend}">
                        {foreach $locale.weekday_name_list as $index => $weekday_name}
                            <option value="{$index}" {if $event[$english_weekday_name_list[$index]]}selected="selected" {/if}>{$weekday_name|wash}</option>
                        {/foreach}
                    </select> {'in'|i18n('blendcalendar')}
                    <select name="{$idstart}yearrelativemonth{$idend}">
                        {for 1 to 12 as $month}
                            {def $dt=makedate($month, 1,2001)}
                            <option {if $event.month|eq($month)}selected="selected" {/if}value="{$month}">{$dt|datetime('custom', '%F')}</option>
                            {undef $dt}
                        {/for}
                    </select>

                </div>
            </div>

            <div class="block bc-element-range" {if $event.recurrence_type|eq(1)}style="display:none" {/if}>
                <label for="{$idstart}interval{$idend}" class="inline">{'Repeat Every'|i18n('blendcalendar')}</label>
                <select name="{$idstart}interval{$idend}" id="{$idstart}interval{$idend}">
                    {for 1 to 10 as $interval}
                        <option {if $event.interval|eq($interval)}selected="selected" {/if}value="{$interval}">{$interval}</option>
                    {/for}
                </select>
                <span class="bc-repeat-type">{switch match=$event.recurrence_type}{case match=2}{'week(s)'|i18n('blendcalendar')}{/case}{case match=array(4,8)}{'month(s)'|i18n('blendcalendar')}{/case}{case match=array(16,32)}{'year(s)'|i18n('blendcalendar')}{/case}{/switch}</span><br />

                <label class="inline" for="{$idstart}rangestart{$idend}">{'starting'|i18n('blendcalendar')}</label>
                <input type="text" name="{$idstart}rangestart{$idend}" id="{$idstart}rangestart{$idend}" class="bc-date" value="{$event.range_start|l10n( 'shortdate' )}" /><br />

            <label class="inline" for="{$idstart}rangeend{$idend}">{'and continuing'|i18n('blendcalendar')}</label>

                <input type="radio" name="{$idstart}rangeendtype{$idend}" id="{$idstart}rangeendtype{$idend}_null" class="bc-rangeendtype-null" value="NULL" {if $event.range_end|not}checked="checked"{/if} />

                <label class="inline" for="{$idstart}rangeendtype{$idend}_null">{'forever'|i18n('blendcalendar')}</label>

                <input type="radio" name="{$idstart}rangeendtype{$idend}" id="{$idstart}rangeendtype{$idend}_date" class="bc-rangeendtype-date" value="DATE" {if $event.range_end}checked="checked"{/if} />
                <label class="inline" for="{$idstart}rangeendtype{$idend}_date">{'until'|i18n('blendcalendar')}</label>

                <input type="text" name="{$idstart}rangeend{$idend}" id="{$idstart}rangeend{$idend}"  {if $event.range_end|not}disabled="disabled"{/if} class="bc-date bc-rangeend-date" value="{cond($event.range_end, $event.range_end, $event.range_start|sum(604800))|l10n('shortdate')}" />
            </div>
        </div><!-- .bc-recurs -->
        <div class="block bc-element-time">
            <strong>{'Time'|i18n('blendcalendar')}</strong><br />
            <label for="{$idstart}timestart{$idend}" class="inline">{'From:'|i18n('blendcalendar')}</label>

            <input type="text" name="{$idstart}timestart{$idend}" id="{$idstart}timestart{$idend}" class="bc-time"
                   value="{$event.start_time_local}"
                    />

            <label for="{$idstart}timestart{$idend}" class="inline">{'To'|i18n('blendcalendar')}</label>
            <input type="text" name="{$idstart}timeend{$idend}" id="{$idstart}timeend{$idend}" class="bc-time"
                   value="{$event.end_time_local}"
                    />

            <input type="checkbox" name="{$idstart}allday{$idend}" id="{$idstart}allday{$idend}" value="1"
                   {if $event.all_day}checked="checked"{/if}
                    />

            <label class="inline" for="{$idstart}allday{$idend}">{'All Day'|i18n('blendcalendar')}</label>

        </div>


    </div><!-- .block -->


{/default}