{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $locale = fetch('content', 'locale')}
{debug-log var=$locale}
{debug-log var=$attribute.content}
{if $attribute.content.recurrence_type|eq( 1 )}{* No reccurence *}
    {sum( $attribute.content.start_time, $attribute.content.range_start )|l10n( 'shortdatetime' )} - {sum( $attribute.content.start_time, $attribute.content.range_start, $attribute.content.duration )|l10n( 'shorttime' )}
{elseif $attribute.content.recurrence_type|eq( 2 )}{* Weekly *}
    {def $week_day_string = ''}
    {if and( $attribute.content.sunday, $attribute.content.monday, $attribute.content.tuesday, $attribute.content.wednesday, $attribute.content.thursday, $attribute.content.friday, $attribute.content.saturday )}
        {set $week_day_string = 'days'|i18n( 'blendcalendar', 'Every DAYS' )}
    {elseif and( $attribute.content.sunday, $attribute.content.saturday )}
        {set $week_day_string = 'weekends'|i18n( 'blendcalendar', 'Every Weekends' )}
    {elseif and( $attribute.content.monday, $attribute.content.tuesday, $attribute.content.wednesday, $attribute.content.thursday, $attribute.content.friday )}
        {set $week_day_string = 'week days'|i18n( 'blendcalendar', 'Every WEEK DAYS' )}
    {else}
        {def $week_day_list = array()}
        {if $attribute.content.sunday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.0 )}
        {/if}
        {if $attribute.content.monday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.1 )}
        {/if}
        {if $attribute.content.tuesday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.2 )}
        {/if}
        {if $attribute.content.wednesday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.3 )}
        {/if}
        {if $attribute.content.thursday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.4 )}
        {/if}
        {if $attribute.content.friday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.5 )}
        {/if}
        {if $attribute.content.saturday}
            {set $week_day_list = $week_day_list|append( $locale.weekday_name_list.6 )}
        {/if}
        {set $week_day_string = $week_day_list|implode( ', ' )}
    {/if}
    {'Every %days%, at %start_time% to %end_time%, from %start_date%'|i18n( 'blendcalendar', 'Do not translate %days%, %start_time, %end_time% and %start_date', hash( '%days%', $week_day_string,
                                                                                                                                                                       '%start_time%', sum( $attribute.content.start_time, $attribute.content.range_start )|l10n( 'shorttime' ),
                                                                                                                                                                       '%end_time%', sum( $attribute.content.start_time, $attribute.content.range_start, $attribute.content.duration )|l10n( 'shorttime' ),
                                                                                                                                                                       '%start_date%', sum( $attribute.content.start_time, $attribute.content.range_start )|l10n( 'shortdate' ) ) )}
    {if $attribute.content.range_end}
        {'to %end_date%'|i18n( 'blendcalendar', 'from %date% to %end_date% : Do not translate %end_date%', hash( '%end_date%', $attribute.content.range_start|l10n( 'shortdate' ) ) )}
    {/if}
    {if $attribute.content.interval|gt( 1 )}
        (1 {'week'|i18n( 'blendcalendar' )} / {$attribute.content.interval})
    {/if}
{elseif $attribute.content.recurrence_type|eq( 4 )}{* Monthly static *}
    {*TODO*}
{elseif $attribute.content.recurrence_type|eq( 8 )}{* Monthly relative *}
    {*TODO*}
{elseif $attribute.content.recurrence_type|eq( 16 )}{* Annual static *}
    {*TODO*}
{elseif $attribute.content.recurrence_type|eq( 32 )}{* Annual relative *}
{/if}